on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@latest
      - name: Build contents
        run: |
          npm run build
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: git-pages
          path: _site
          retention-days: 1
          overwrite: true
