on:
  push:
    branches:
      - master
      - feat/deploy-pages

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/configure-pages@v5
      
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
      - run: |
          PREFIX=$(git rev-parse --show-toplevel | xargs basename)
          echo "PATH_PREFIX=${PREFIX}" >> $GITHUB_ENV
      - run: |
          npm install
          npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'
      - id: deployment
        uses: actions/deploy-pages@v4
